-- FYRK Agent Platform - Initial Schema
-- Creates tables for agent runs and artifacts

create extension if not exists pgcrypto;

create table if not exists agent_runs (
  id uuid primary key default gen_random_uuid(),
  agent_name text not null,
  agent_version text not null,
  status text not null default 'started',
  input jsonb not null default '{}'::jsonb,
  output jsonb not null default '{}'::jsonb,
  error text,
  created_at timestamptz default now(),
  finished_at timestamptz
);

create table if not exists artifacts (
  id uuid primary key default gen_random_uuid(),
  run_id uuid references agent_runs(id) on delete cascade,
  kind text not null,
  content text not null,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz default now()
);

create index if not exists idx_agent_runs_agent_name on agent_runs(agent_name);
create index if not exists idx_agent_runs_status on agent_runs(status);
create index if not exists idx_agent_runs_created_at on agent_runs(created_at);
create index if not exists idx_artifacts_run_id on artifacts(run_id);
create index if not exists idx_artifacts_kind on artifacts(kind);

-- Add comments for documentation
comment on table agent_runs is 'Stores execution records for all agent runs';
comment on table artifacts is 'Stores output artifacts generated by agent runs';
comment on column agent_runs.status is 'Run status: started, completed, failed';
comment on column artifacts.kind is 'Artifact type: markdown, json, etc.';
